CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE aboneler (
    abone_id bigint GENERATED BY DEFAULT AS IDENTITY,
    abone_no text NOT NULL,
    abone_tipi text NOT NULL,
    ad text,
    soyad text,
    unvan text,
    tckn text,
    vkn text,
    telefon text,
    e_posta text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT "PK_aboneler" PRIMARY KEY (abone_id)
);

CREATE TABLE "Bildirimler" (
    "BildirimId" integer GENERATED BY DEFAULT AS IDENTITY,
    "KullaniciId" integer NOT NULL,
    "Baslik" character varying(200) NOT NULL,
    "Icerik" text NOT NULL,
    "OkunduMu" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Bildirimler" PRIMARY KEY ("BildirimId")
);

CREATE TABLE il (
    il_id smallint GENERATED BY DEFAULT AS IDENTITY,
    il_adi character varying(50) NOT NULL,
    plaka_kodu smallint,
    CONSTRAINT pk_il PRIMARY KEY (il_id)
);

CREATE TABLE roller (
    rol_id smallint GENERATED BY DEFAULT AS IDENTITY,
    rol_adi character varying(50) NOT NULL,
    aciklama character varying(255),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_roller PRIMARY KEY (rol_id)
);

CREATE TABLE tarifeler (
    tarife_id bigint GENERATED BY DEFAULT AS IDENTITY,
    tarife_kodu text NOT NULL,
    tarife_adi text NOT NULL,
    gunduz_birim_fiyat numeric NOT NULL,
    puant_birim_fiyat numeric,
    gece_birim_fiyat numeric,
    induktif_birim_fiyat numeric,
    kapasitif_birim_fiyat numeric,
    demand_birim_fiyat numeric,
    kdv_orani numeric NOT NULL,
    dagitim_bedeli numeric NOT NULL,
    aktif boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT "PK_tarifeler" PRIMARY KEY (tarife_id)
);

CREATE TABLE ilce (
    ilce_id integer GENERATED BY DEFAULT AS IDENTITY,
    il_id smallint NOT NULL,
    ilce_adi character varying(50) NOT NULL,
    CONSTRAINT pk_ilce PRIMARY KEY (ilce_id),
    CONSTRAINT fk_ilce_il FOREIGN KEY (il_id) REFERENCES il (il_id)
);

CREATE TABLE kullanicilar (
    kullanici_id bigint GENERATED BY DEFAULT AS IDENTITY,
    rol_id smallint NOT NULL,
    ad_soyad character varying(150) NOT NULL,
    e_posta character varying(150) NOT NULL,
    kullanici_adi character varying(50) NOT NULL,
    sifre_hash character varying(255) NOT NULL,
    durum character varying(20) NOT NULL DEFAULT ('AKTIF'::character varying),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT pk_kullanicilar PRIMARY KEY (kullanici_id),
    CONSTRAINT fk_kullanicilar_roller FOREIGN KEY (rol_id) REFERENCES roller (rol_id)
);

CREATE TABLE audit_log (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY,
    varlik_tipi character varying(50) NOT NULL,
    varlik_id bigint NOT NULL,
    islem_tipi character varying(20) NOT NULL,
    eski_deger jsonb,
    yeni_deger jsonb,
    kullanici_id bigint,
    islem_gerekcesi character varying(255),
    islem_zamani timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_audit_log PRIMARY KEY (audit_id),
    CONSTRAINT fk_audit_log_kullanici FOREIGN KEY (kullanici_id) REFERENCES kullanicilar (kullanici_id)
);

CREATE TABLE tuketim_noktasi (
    tuketim_noktasi_id bigint GENERATED BY DEFAULT AS IDENTITY,
    tekil_kod text NOT NULL,
    ilce_id integer NOT NULL,
    mahalle text NOT NULL,
    bina_no text,
    bagimsiz_bolum_no text,
    acik_adres text NOT NULL,
    koordinat_lat numeric,
    koordinat_lon numeric,
    baglanti_gucu_kw numeric NOT NULL,
    tuketici_grubu text NOT NULL,
    baglanti_durumu text NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    updated_at timestamp with time zone,
    updated_by bigint,
    CONSTRAINT "PK_tuketim_noktasi" PRIMARY KEY (tuketim_noktasi_id),
    CONSTRAINT "FK_tuketim_noktasi_ilce_ilce_id" FOREIGN KEY (ilce_id) REFERENCES ilce (ilce_id) ON DELETE CASCADE,
    CONSTRAINT "FK_tuketim_noktasi_kullanicilar_created_by" FOREIGN KEY (created_by) REFERENCES kullanicilar (kullanici_id),
    CONSTRAINT "FK_tuketim_noktasi_kullanicilar_updated_by" FOREIGN KEY (updated_by) REFERENCES kullanicilar (kullanici_id)
);

CREATE TABLE sayaclar (
    sayac_id bigint GENERATED BY DEFAULT AS IDENTITY,
    seri_no text NOT NULL,
    tuketim_noktasi_id bigint,
    marka text,
    model text,
    uretim_yili integer NOT NULL,
    faz text,
    carpan numeric NOT NULL,
    muhur_no text,
    durum text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by bigint,
    updated_at timestamp with time zone,
    updated_by bigint,
    CONSTRAINT "PK_sayaclar" PRIMARY KEY (sayac_id),
    CONSTRAINT "FK_sayaclar_kullanicilar_created_by" FOREIGN KEY (created_by) REFERENCES kullanicilar (kullanici_id),
    CONSTRAINT "FK_sayaclar_kullanicilar_updated_by" FOREIGN KEY (updated_by) REFERENCES kullanicilar (kullanici_id),
    CONSTRAINT "FK_sayaclar_tuketim_noktasi_tuketim_noktasi_id" FOREIGN KEY (tuketim_noktasi_id) REFERENCES tuketim_noktasi (tuketim_noktasi_id)
);

CREATE TABLE sozlesmeler (
    sozlesme_id bigint GENERATED BY DEFAULT AS IDENTITY,
    sozlesme_no text NOT NULL,
    tuketim_noktasi_id bigint NOT NULL,
    abone_id bigint NOT NULL,
    tarife_id bigint NOT NULL,
    sozlesme_tipi text NOT NULL,
    durum text NOT NULL,
    baslangic_tarihi date NOT NULL,
    bitis_tarihi date,
    guvence_bedeli numeric NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT "PK_sozlesmeler" PRIMARY KEY (sozlesme_id),
    CONSTRAINT "FK_sozlesmeler_aboneler_abone_id" FOREIGN KEY (abone_id) REFERENCES aboneler (abone_id) ON DELETE CASCADE,
    CONSTRAINT "FK_sozlesmeler_tarifeler_tarife_id" FOREIGN KEY (tarife_id) REFERENCES tarifeler (tarife_id) ON DELETE CASCADE,
    CONSTRAINT "FK_sozlesmeler_tuketim_noktasi_tuketim_noktasi_id" FOREIGN KEY (tuketim_noktasi_id) REFERENCES tuketim_noktasi (tuketim_noktasi_id) ON DELETE CASCADE
);

CREATE TABLE is_emirleri (
    is_emri_id bigint GENERATED BY DEFAULT AS IDENTITY,
    is_emri_no text NOT NULL,
    tuketim_noktasi_id bigint NOT NULL,
    sayac_id bigint,
    tip text NOT NULL,
    oncelik text NOT NULL,
    planlanan_tarih timestamp with time zone,
    atanan_kullanici_id bigint,
    durum text NOT NULL,
    saha_sonucu text,
    gerekce text,
    muhur_no text,
    tutanak_no text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    sokulen_seri_no text,
    yeni_seri_no text,
    yeni_muhur_no text,
    eski_muhur_no text,
    damga_yili integer,
    akim_trafosu_seri_no text,
    akim_trafosu_marka text,
    gerilim_trafosu_seri_no text,
    gerilim_trafosu_marka text,
    ariza_tipi text,
    kesme_noktasi text,
    kesme_nedeni text,
    abone_durumu text,
    sayac_durumu text,
    pano_direk_no text,
    kesif_sonucu text,
    yapi_tesis_tipi text,
    hat_mesafesi text,
    talep_gucu text,
    inceleme_notu text,
    acma_noktasi text,
    CONSTRAINT "PK_is_emirleri" PRIMARY KEY (is_emri_id),
    CONSTRAINT "FK_is_emirleri_kullanicilar_atanan_kullanici_id" FOREIGN KEY (atanan_kullanici_id) REFERENCES kullanicilar (kullanici_id),
    CONSTRAINT "FK_is_emirleri_sayaclar_sayac_id" FOREIGN KEY (sayac_id) REFERENCES sayaclar (sayac_id),
    CONSTRAINT "FK_is_emirleri_tuketim_noktasi_tuketim_noktasi_id" FOREIGN KEY (tuketim_noktasi_id) REFERENCES tuketim_noktasi (tuketim_noktasi_id) ON DELETE CASCADE
);

CREATE TABLE endeks_okuma (
    okuma_id bigint GENERATED BY DEFAULT AS IDENTITY,
    sayac_id bigint NOT NULL,
    is_emri_id bigint,
    sozlesme_id bigint,
    okuma_tipi text NOT NULL,
    okuma_kaynagi text NOT NULL,
    onceki_endeks numeric,
    yeni_endeks numeric NOT NULL,
    donem text,
    okuma_zamani timestamp with time zone NOT NULL,
    kullanici_id bigint,
    okunamama_nedeni text,
    dogrulama_durumu text NOT NULL,
    anomali_mi boolean NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_endeks_okuma" PRIMARY KEY (okuma_id),
    CONSTRAINT "FK_endeks_okuma_is_emirleri_is_emri_id" FOREIGN KEY (is_emri_id) REFERENCES is_emirleri (is_emri_id),
    CONSTRAINT "FK_endeks_okuma_kullanicilar_kullanici_id" FOREIGN KEY (kullanici_id) REFERENCES kullanicilar (kullanici_id),
    CONSTRAINT "FK_endeks_okuma_sayaclar_sayac_id" FOREIGN KEY (sayac_id) REFERENCES sayaclar (sayac_id) ON DELETE CASCADE,
    CONSTRAINT "FK_endeks_okuma_sozlesmeler_sozlesme_id" FOREIGN KEY (sozlesme_id) REFERENCES sozlesmeler (sozlesme_id)
);

CREATE TABLE fatura (
    fatura_id bigint GENERATED BY DEFAULT AS IDENTITY,
    fatura_no character varying(40) NOT NULL,
    sozlesme_id bigint NOT NULL,
    tekil_kod character varying(40) NOT NULL,
    fatura_tipi character varying(20) NOT NULL DEFAULT ('DONEM'::character varying),
    donem character varying(7) NOT NULL,
    fatura_tarihi date NOT NULL,
    son_odeme_tarihi date NOT NULL,
    okuma_id bigint,
    ilk_endeks numeric(14,3),
    son_endeks numeric(14,3),
    tuketim_kwh numeric(14,3),
    reaktif_enduktif numeric(14,3),
    reaktif_kapasitif numeric(14,3),
    carpan numeric(10,3),
    enerji_bedeli numeric(14,2) NOT NULL,
    dagitim_bedeli numeric(14,2) NOT NULL,
    hizmet_bedeli numeric(14,2) NOT NULL,
    kesme_baglama_bedeli numeric(14,2) NOT NULL,
    vergi_fon_toplam numeric(14,2) NOT NULL,
    toplam_tutar numeric(14,2) NOT NULL,
    durum character varying(20) NOT NULL DEFAULT ('TASLAK'::character varying),
    status character varying(20) NOT NULL DEFAULT ('AKTIF'::character varying),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT pk_fatura PRIMARY KEY (fatura_id),
    CONSTRAINT fk_fatura_okuma FOREIGN KEY (okuma_id) REFERENCES endeks_okuma (okuma_id),
    CONSTRAINT fk_fatura_sozlesme FOREIGN KEY (sozlesme_id) REFERENCES sozlesmeler (sozlesme_id)
);

CREATE TABLE entegrasyon_outbox (
    outbox_id bigint GENERATED BY DEFAULT AS IDENTITY,
    fatura_id bigint NOT NULL,
    hedef_sistem character varying(30) NOT NULL,
    idempotency_key character varying(100) NOT NULL,
    correlation_id character varying(100),
    payload jsonb,
    durum character varying(20) NOT NULL DEFAULT ('BEKLIYOR'::character varying),
    hata_kodu character varying(30),
    hata_mesaji character varying(500),
    retry_count integer NOT NULL,
    son_deneme_tarihi timestamp with time zone,
    gonderim_zamani timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_entegrasyon_outbox PRIMARY KEY (outbox_id),
    CONSTRAINT fk_entegrasyon_outbox_fatura FOREIGN KEY (fatura_id) REFERENCES fatura (fatura_id)
);

CREATE TABLE fatura_kalemi (
    fatura_kalem_id bigint GENERATED BY DEFAULT AS IDENTITY,
    fatura_id bigint NOT NULL,
    kalem_tipi character varying(30) NOT NULL,
    aciklama character varying(255),
    miktar numeric(14,3) NOT NULL,
    birim_fiyat numeric(14,4),
    tutar numeric(14,2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_fatura_kalemi PRIMARY KEY (fatura_kalem_id),
    CONSTRAINT fk_fatura_kalemi_fatura FOREIGN KEY (fatura_id) REFERENCES fatura (fatura_id) ON DELETE CASCADE
);

CREATE INDEX "IX_audit_log_kullanici_id" ON audit_log (kullanici_id);

CREATE INDEX idx_audit_log_varlik ON audit_log (varlik_tipi, varlik_id);

CREATE INDEX "IX_endeks_okuma_is_emri_id" ON endeks_okuma (is_emri_id);

CREATE INDEX "IX_endeks_okuma_kullanici_id" ON endeks_okuma (kullanici_id);

CREATE INDEX "IX_endeks_okuma_sayac_id" ON endeks_okuma (sayac_id);

CREATE INDEX "IX_endeks_okuma_sozlesme_id" ON endeks_okuma (sozlesme_id);

CREATE INDEX "IX_entegrasyon_outbox_fatura_id" ON entegrasyon_outbox (fatura_id);

CREATE INDEX idx_entegrasyon_outbox_durum ON entegrasyon_outbox (durum);

CREATE UNIQUE INDEX uq_entegrasyon_outbox_idempotency ON entegrasyon_outbox (idempotency_key);

CREATE INDEX "IX_fatura_okuma_id" ON fatura (okuma_id);

CREATE INDEX idx_fatura_donem ON fatura (donem);

CREATE INDEX idx_fatura_durum ON fatura (durum);

CREATE INDEX idx_fatura_sozlesme_id ON fatura (sozlesme_id);

CREATE UNIQUE INDEX uq_fatura_fatura_no ON fatura (fatura_no);

CREATE INDEX "IX_fatura_kalemi_fatura_id" ON fatura_kalemi (fatura_id);

CREATE UNIQUE INDEX uq_il_il_adi ON il (il_adi);

CREATE INDEX idx_ilce_il_id ON ilce (il_id);

CREATE UNIQUE INDEX uq_ilce_il_adi ON ilce (il_id, ilce_adi);

CREATE INDEX "IX_is_emirleri_atanan_kullanici_id" ON is_emirleri (atanan_kullanici_id);

CREATE INDEX "IX_is_emirleri_sayac_id" ON is_emirleri (sayac_id);

CREATE INDEX "IX_is_emirleri_tuketim_noktasi_id" ON is_emirleri (tuketim_noktasi_id);

CREATE INDEX idx_kullanicilar_rol_id ON kullanicilar (rol_id);

CREATE UNIQUE INDEX uq_kullanicilar_e_posta ON kullanicilar (e_posta);

CREATE UNIQUE INDEX uq_kullanicilar_kullanici_adi ON kullanicilar (kullanici_adi);

CREATE UNIQUE INDEX uq_roller_rol_adi ON roller (rol_adi);

CREATE INDEX "IX_sayaclar_created_by" ON sayaclar (created_by);

CREATE INDEX "IX_sayaclar_tuketim_noktasi_id" ON sayaclar (tuketim_noktasi_id);

CREATE INDEX "IX_sayaclar_updated_by" ON sayaclar (updated_by);

CREATE INDEX "IX_sozlesmeler_abone_id" ON sozlesmeler (abone_id);

CREATE INDEX "IX_sozlesmeler_tarife_id" ON sozlesmeler (tarife_id);

CREATE INDEX "IX_sozlesmeler_tuketim_noktasi_id" ON sozlesmeler (tuketim_noktasi_id);

CREATE INDEX "IX_tuketim_noktasi_created_by" ON tuketim_noktasi (created_by);

CREATE INDEX "IX_tuketim_noktasi_ilce_id" ON tuketim_noktasi (ilce_id);

CREATE INDEX "IX_tuketim_noktasi_updated_by" ON tuketim_noktasi (updated_by);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260720132705_BildirimlerTablosuEklendi', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Bildirimler" DROP CONSTRAINT "PK_Bildirimler";

ALTER TABLE "Bildirimler" RENAME TO bildirimler;

ALTER TABLE bildirimler ADD is_emri_id bigint;

ALTER TABLE bildirimler ADD CONSTRAINT "PK_bildirimler" PRIMARY KEY ("BildirimId");

CREATE INDEX idx_aboneler_telefon ON aboneler (telefon);

CREATE UNIQUE INDEX uq_aboneler_abone_no ON aboneler (abone_no);

CREATE UNIQUE INDEX uq_aboneler_tckn ON aboneler (tckn);

CREATE UNIQUE INDEX uq_aboneler_vkn ON aboneler (vkn);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260723122714_AbonelerIndexEklendi', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER INDEX "IX_sozlesmeler_tuketim_noktasi_id" RENAME TO idx_sozlesmeler_tuketim_id;

ALTER INDEX "IX_sozlesmeler_abone_id" RENAME TO idx_sozlesmeler_abone_id;

ALTER INDEX "IX_sayaclar_tuketim_noktasi_id" RENAME TO idx_sayaclar_tuketim_id;

ALTER INDEX "IX_is_emirleri_tuketim_noktasi_id" RENAME TO idx_isemirleri_tuketim_id;

ALTER INDEX "IX_is_emirleri_atanan_kullanici_id" RENAME TO idx_isemirleri_atanan_id;

ALTER INDEX "IX_endeks_okuma_sozlesme_id" RENAME TO idx_endeks_sozlesme_id;

ALTER INDEX "IX_endeks_okuma_sayac_id" RENAME TO idx_endeks_sayac_id;

CREATE INDEX idx_sozlesmeler_durum ON sozlesmeler (durum);

CREATE UNIQUE INDEX uq_sozlesmeler_sozlesme_no ON sozlesmeler (sozlesme_no);

CREATE UNIQUE INDEX uq_sayaclar_seri_no ON sayaclar (seri_no);

CREATE INDEX idx_isemirleri_durum ON is_emirleri (durum);

CREATE UNIQUE INDEX uq_isemirleri_no ON is_emirleri (is_emri_no);

CREATE INDEX idx_endeks_donem ON endeks_okuma (donem);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260724051249_TümIndeks', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE aboneler ADD status text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260730061444_AddAboneStatusColumn', '10.0.9');

COMMIT;

