// <auto-generated />
using System;
using KcetasAboneApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KcetasAboneApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KcetasAboneApi.Models.Aboneler", b =>
                {
                    b.Property<long>("AboneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("abone_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AboneId"));

                    b.Property<string>("AboneNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abone_no");

                    b.Property<string>("AboneTipi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abone_tipi");

                    b.Property<string>("Ad")
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EPosta")
                        .HasColumnType("text")
                        .HasColumnName("e_posta");

                    b.Property<string>("Soyad")
                        .HasColumnType("text")
                        .HasColumnName("soyad");

                    b.Property<string>("Tckn")
                        .HasColumnType("text")
                        .HasColumnName("tckn");

                    b.Property<string>("Telefon")
                        .HasColumnType("text")
                        .HasColumnName("telefon");

                    b.Property<string>("Unvan")
                        .HasColumnType("text")
                        .HasColumnName("unvan");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vkn")
                        .HasColumnType("text")
                        .HasColumnName("vkn");

                    b.HasKey("AboneId");

                    b.ToTable("aboneler");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditId"));

                    b.Property<string>("EskiDeger")
                        .HasColumnType("jsonb")
                        .HasColumnName("eski_deger");

                    b.Property<string>("IslemGerekcesi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("islem_gerekcesi");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("islem_tipi");

                    b.Property<DateTime>("IslemZamani")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("islem_zamani")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("KullaniciId")
                        .HasColumnType("bigint")
                        .HasColumnName("kullanici_id");

                    b.Property<long>("VarlikId")
                        .HasColumnType("bigint")
                        .HasColumnName("varlik_id");

                    b.Property<string>("VarlikTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("varlik_tipi");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("jsonb")
                        .HasColumnName("yeni_deger");

                    b.HasKey("AuditId")
                        .HasName("pk_audit_log");

                    b.HasIndex("KullaniciId");

                    b.HasIndex(new[] { "VarlikTipi", "VarlikId" }, "idx_audit_log_varlik");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Bildirim", b =>
                {
                    b.Property<int>("BildirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BildirimId"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("boolean");

                    b.HasKey("BildirimId");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.EndeksOkuma", b =>
                {
                    b.Property<long>("OkumaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("okuma_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OkumaId"));

                    b.Property<bool>("AnomaliMi")
                        .HasColumnType("boolean")
                        .HasColumnName("anomali_mi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DogrulamaDurumu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dogrulama_durumu");

                    b.Property<string>("Donem")
                        .HasColumnType("text")
                        .HasColumnName("donem");

                    b.Property<long?>("IsEmriId")
                        .HasColumnType("bigint")
                        .HasColumnName("is_emri_id");

                    b.Property<long?>("KullaniciId")
                        .HasColumnType("bigint")
                        .HasColumnName("kullanici_id");

                    b.Property<string>("OkumaKaynagi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("okuma_kaynagi");

                    b.Property<string>("OkumaTipi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("okuma_tipi");

                    b.Property<DateTime>("OkumaZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("okuma_zamani");

                    b.Property<string>("OkunamamaNedeni")
                        .HasColumnType("text")
                        .HasColumnName("okunamama_nedeni");

                    b.Property<decimal?>("OncekiEndeks")
                        .HasColumnType("numeric")
                        .HasColumnName("onceki_endeks");

                    b.Property<long>("SayacId")
                        .HasColumnType("bigint")
                        .HasColumnName("sayac_id");

                    b.Property<long?>("SozlesmeId")
                        .HasColumnType("bigint")
                        .HasColumnName("sozlesme_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("YeniEndeks")
                        .HasColumnType("numeric")
                        .HasColumnName("yeni_endeks");

                    b.HasKey("OkumaId");

                    b.HasIndex("IsEmriId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SayacId");

                    b.HasIndex("SozlesmeId");

                    b.ToTable("endeks_okuma");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.EntegrasyonOutbox", b =>
                {
                    b.Property<long>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("outbox_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OutboxId"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("durum")
                        .HasDefaultValueSql("'BEKLIYOR'::character varying");

                    b.Property<long>("FaturaId")
                        .HasColumnType("bigint")
                        .HasColumnName("fatura_id");

                    b.Property<DateTime?>("GonderimZamani")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gonderim_zamani");

                    b.Property<string>("HataKodu")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("hata_kodu");

                    b.Property<string>("HataMesaji")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hata_mesaji");

                    b.Property<string>("HedefSistem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("hedef_sistem");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SonDenemeTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("son_deneme_tarihi");

                    b.HasKey("OutboxId")
                        .HasName("pk_entegrasyon_outbox");

                    b.HasIndex("FaturaId");

                    b.HasIndex(new[] { "Durum" }, "idx_entegrasyon_outbox_durum");

                    b.HasIndex(new[] { "IdempotencyKey" }, "uq_entegrasyon_outbox_idempotency")
                        .IsUnique();

                    b.ToTable("entegrasyon_outbox", (string)null);
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Fatura", b =>
                {
                    b.Property<long>("FaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fatura_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FaturaId"));

                    b.Property<decimal?>("Carpan")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("carpan");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DagitimBedeli")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("dagitim_bedeli");

                    b.Property<string>("Donem")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("donem");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("durum")
                        .HasDefaultValueSql("'TASLAK'::character varying");

                    b.Property<decimal>("EnerjiBedeli")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("enerji_bedeli");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("fatura_no");

                    b.Property<DateOnly>("FaturaTarihi")
                        .HasColumnType("date")
                        .HasColumnName("fatura_tarihi");

                    b.Property<string>("FaturaTipi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fatura_tipi")
                        .HasDefaultValueSql("'DONEM'::character varying");

                    b.Property<decimal>("HizmetBedeli")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("hizmet_bedeli");

                    b.Property<decimal?>("IlkEndeks")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("ilk_endeks");

                    b.Property<decimal>("KesmeBaglamaBedeli")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("kesme_baglama_bedeli");

                    b.Property<long?>("OkumaId")
                        .HasColumnType("bigint")
                        .HasColumnName("okuma_id");

                    b.Property<decimal?>("ReaktifEnduktif")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("reaktif_enduktif");

                    b.Property<decimal?>("ReaktifKapasitif")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("reaktif_kapasitif");

                    b.Property<decimal?>("SonEndeks")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("son_endeks");

                    b.Property<DateOnly>("SonOdemeTarihi")
                        .HasColumnType("date")
                        .HasColumnName("son_odeme_tarihi");

                    b.Property<long>("SozlesmeId")
                        .HasColumnType("bigint")
                        .HasColumnName("sozlesme_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'AKTIF'::character varying");

                    b.Property<string>("TekilKod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tekil_kod");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("toplam_tutar");

                    b.Property<decimal?>("TuketimKwh")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("tuketim_kwh");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VergiFonToplam")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("vergi_fon_toplam");

                    b.HasKey("FaturaId")
                        .HasName("pk_fatura");

                    b.HasIndex("OkumaId");

                    b.HasIndex(new[] { "Donem" }, "idx_fatura_donem");

                    b.HasIndex(new[] { "Durum" }, "idx_fatura_durum");

                    b.HasIndex(new[] { "SozlesmeId" }, "idx_fatura_sozlesme_id");

                    b.HasIndex(new[] { "FaturaNo" }, "uq_fatura_fatura_no")
                        .IsUnique();

                    b.ToTable("fatura", (string)null);
                });

            modelBuilder.Entity("KcetasAboneApi.Models.FaturaKalemi", b =>
                {
                    b.Property<long>("FaturaKalemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fatura_kalem_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FaturaKalemId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("aciklama");

                    b.Property<decimal?>("BirimFiyat")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("birim_fiyat");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("FaturaId")
                        .HasColumnType("bigint")
                        .HasColumnName("fatura_id");

                    b.Property<string>("KalemTipi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kalem_tipi");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)")
                        .HasColumnName("miktar");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("tutar");

                    b.HasKey("FaturaKalemId")
                        .HasName("pk_fatura_kalemi");

                    b.HasIndex("FaturaId");

                    b.ToTable("fatura_kalemi", (string)null);
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Il", b =>
                {
                    b.Property<short>("IlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("il_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IlId"));

                    b.Property<string>("IlAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("il_adi");

                    b.Property<short?>("PlakaKodu")
                        .HasColumnType("smallint")
                        .HasColumnName("plaka_kodu");

                    b.HasKey("IlId")
                        .HasName("pk_il");

                    b.HasIndex(new[] { "IlAdi" }, "uq_il_il_adi")
                        .IsUnique();

                    b.ToTable("il", (string)null);
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Ilce", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ilce_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IlceId"));

                    b.Property<short>("IlId")
                        .HasColumnType("smallint")
                        .HasColumnName("il_id");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ilce_adi");

                    b.HasKey("IlceId")
                        .HasName("pk_ilce");

                    b.HasIndex(new[] { "IlId" }, "idx_ilce_il_id");

                    b.HasIndex(new[] { "IlId", "IlceAdi" }, "uq_ilce_il_adi")
                        .IsUnique();

                    b.ToTable("ilce", (string)null);
                });

            modelBuilder.Entity("KcetasAboneApi.Models.IsEmirleri", b =>
                {
                    b.Property<long>("IsEmriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("is_emri_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IsEmriId"));

                    b.Property<string>("AboneDurumu")
                        .HasColumnType("text")
                        .HasColumnName("abone_durumu");

                    b.Property<string>("AcmaNoktasi")
                        .HasColumnType("text")
                        .HasColumnName("acma_noktasi");

                    b.Property<string>("AkimTrafosuMarka")
                        .HasColumnType("text")
                        .HasColumnName("akim_trafosu_marka");

                    b.Property<string>("AkimTrafosuSeriNo")
                        .HasColumnType("text")
                        .HasColumnName("akim_trafosu_seri_no");

                    b.Property<string>("ArizaTipi")
                        .HasColumnType("text")
                        .HasColumnName("ariza_tipi");

                    b.Property<long?>("AtananKullaniciId")
                        .HasColumnType("bigint")
                        .HasColumnName("atanan_kullanici_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DamgaYili")
                        .HasColumnType("integer")
                        .HasColumnName("damga_yili");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("durum");

                    b.Property<string>("EskiMuhurNo")
                        .HasColumnType("text")
                        .HasColumnName("eski_muhur_no");

                    b.Property<string>("Gerekce")
                        .HasColumnType("text")
                        .HasColumnName("gerekce");

                    b.Property<string>("GerilimTrafosuMarka")
                        .HasColumnType("text")
                        .HasColumnName("gerilim_trafosu_marka");

                    b.Property<string>("GerilimTrafosuSeriNo")
                        .HasColumnType("text")
                        .HasColumnName("gerilim_trafosu_seri_no");

                    b.Property<string>("HatMesafesi")
                        .HasColumnType("text")
                        .HasColumnName("hat_mesafesi");

                    b.Property<string>("IncelemeNotu")
                        .HasColumnType("text")
                        .HasColumnName("inceleme_notu");

                    b.Property<string>("IsEmriNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("is_emri_no");

                    b.Property<string>("KesifSonucu")
                        .HasColumnType("text")
                        .HasColumnName("kesif_sonucu");

                    b.Property<string>("KesmeNedeni")
                        .HasColumnType("text")
                        .HasColumnName("kesme_nedeni");

                    b.Property<string>("KesmeNoktasi")
                        .HasColumnType("text")
                        .HasColumnName("kesme_noktasi");

                    b.Property<string>("MuhurNo")
                        .HasColumnType("text")
                        .HasColumnName("muhur_no");

                    b.Property<string>("Oncelik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oncelik");

                    b.Property<string>("PanoDirekNo")
                        .HasColumnType("text")
                        .HasColumnName("pano_direk_no");

                    b.Property<DateTime?>("PlanlananTarih")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planlanan_tarih");

                    b.Property<string>("SahaSonucu")
                        .HasColumnType("text")
                        .HasColumnName("saha_sonucu");

                    b.Property<string>("SayacDurumu")
                        .HasColumnType("text")
                        .HasColumnName("sayac_durumu");

                    b.Property<long?>("SayacId")
                        .HasColumnType("bigint")
                        .HasColumnName("sayac_id");

                    b.Property<string>("SokulenSeriNo")
                        .HasColumnType("text")
                        .HasColumnName("sokulen_seri_no");

                    b.Property<string>("TalepGucu")
                        .HasColumnType("text")
                        .HasColumnName("talep_gucu");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tip");

                    b.Property<long>("TuketimNoktasiId")
                        .HasColumnType("bigint")
                        .HasColumnName("tuketim_noktasi_id");

                    b.Property<string>("TutanakNo")
                        .HasColumnType("text")
                        .HasColumnName("tutanak_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YapiTesisTipi")
                        .HasColumnType("text")
                        .HasColumnName("yapi_tesis_tipi");

                    b.Property<string>("YeniMuhurNo")
                        .HasColumnType("text")
                        .HasColumnName("yeni_muhur_no");

                    b.Property<string>("YeniSeriNo")
                        .HasColumnType("text")
                        .HasColumnName("yeni_seri_no");

                    b.HasKey("IsEmriId");

                    b.HasIndex("AtananKullaniciId");

                    b.HasIndex("SayacId");

                    b.HasIndex("TuketimNoktasiId");

                    b.ToTable("is_emirleri");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Kullanicilar", b =>
                {
                    b.Property<long>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("kullanici_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ad_soyad");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("durum")
                        .HasDefaultValueSql("'AKTIF'::character varying");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("e_posta");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kullanici_adi");

                    b.Property<short>("RolId")
                        .HasColumnType("smallint")
                        .HasColumnName("rol_id");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sifre_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("KullaniciId")
                        .HasName("pk_kullanicilar");

                    b.HasIndex(new[] { "RolId" }, "idx_kullanicilar_rol_id");

                    b.HasIndex(new[] { "EPosta" }, "uq_kullanicilar_e_posta")
                        .IsUnique();

                    b.HasIndex(new[] { "KullaniciAdi" }, "uq_kullanicilar_kullanici_adi")
                        .IsUnique();

                    b.ToTable("kullanicilar", (string)null);
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Roller", b =>
                {
                    b.Property<short>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("RolId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("aciklama");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol_adi");

                    b.HasKey("RolId")
                        .HasName("pk_roller");

                    b.HasIndex(new[] { "RolAdi" }, "uq_roller_rol_adi")
                        .IsUnique();

                    b.ToTable("roller", (string)null);
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Sayaclar", b =>
                {
                    b.Property<long>("SayacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sayac_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SayacId"));

                    b.Property<decimal>("Carpan")
                        .HasColumnType("numeric")
                        .HasColumnName("carpan");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("durum");

                    b.Property<string>("Faz")
                        .HasColumnType("text")
                        .HasColumnName("faz");

                    b.Property<string>("Marka")
                        .HasColumnType("text")
                        .HasColumnName("marka");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("MuhurNo")
                        .HasColumnType("text")
                        .HasColumnName("muhur_no");

                    b.Property<string>("SeriNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seri_no");

                    b.Property<long?>("TuketimNoktasiId")
                        .HasColumnType("bigint")
                        .HasColumnName("tuketim_noktasi_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<int>("UretimYili")
                        .HasColumnType("integer")
                        .HasColumnName("uretim_yili");

                    b.HasKey("SayacId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TuketimNoktasiId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("sayaclar");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Sozlesmeler", b =>
                {
                    b.Property<long>("SozlesmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sozlesme_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SozlesmeId"));

                    b.Property<long>("AboneId")
                        .HasColumnType("bigint")
                        .HasColumnName("abone_id");

                    b.Property<DateOnly>("BaslangicTarihi")
                        .HasColumnType("date")
                        .HasColumnName("baslangic_tarihi");

                    b.Property<DateOnly?>("BitisTarihi")
                        .HasColumnType("date")
                        .HasColumnName("bitis_tarihi");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("durum");

                    b.Property<decimal>("GuvenceBedeli")
                        .HasColumnType("numeric")
                        .HasColumnName("guvence_bedeli");

                    b.Property<string>("SozlesmeNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sozlesme_no");

                    b.Property<string>("SozlesmeTipi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sozlesme_tipi");

                    b.Property<long>("TarifeId")
                        .HasColumnType("bigint")
                        .HasColumnName("tarife_id");

                    b.Property<long>("TuketimNoktasiId")
                        .HasColumnType("bigint")
                        .HasColumnName("tuketim_noktasi_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SozlesmeId");

                    b.HasIndex("AboneId");

                    b.HasIndex("TarifeId");

                    b.HasIndex("TuketimNoktasiId");

                    b.ToTable("sozlesmeler");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Tarifeler", b =>
                {
                    b.Property<long>("TarifeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tarife_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TarifeId"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DagitimBedeli")
                        .HasColumnType("numeric")
                        .HasColumnName("dagitim_bedeli");

                    b.Property<decimal?>("DemandBirimFiyat")
                        .HasColumnType("numeric")
                        .HasColumnName("demand_birim_fiyat");

                    b.Property<decimal?>("GeceBirimFiyat")
                        .HasColumnType("numeric")
                        .HasColumnName("gece_birim_fiyat");

                    b.Property<decimal>("GunduzBirimFiyat")
                        .HasColumnType("numeric")
                        .HasColumnName("gunduz_birim_fiyat");

                    b.Property<decimal?>("InduktifBirimFiyat")
                        .HasColumnType("numeric")
                        .HasColumnName("induktif_birim_fiyat");

                    b.Property<decimal?>("KapasitifBirimFiyat")
                        .HasColumnType("numeric")
                        .HasColumnName("kapasitif_birim_fiyat");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("numeric")
                        .HasColumnName("kdv_orani");

                    b.Property<decimal?>("PuantBirimFiyat")
                        .HasColumnType("numeric")
                        .HasColumnName("puant_birim_fiyat");

                    b.Property<string>("TarifeAdi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tarife_adi");

                    b.Property<string>("TarifeKodu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tarife_kodu");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TarifeId");

                    b.ToTable("tarifeler");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.TuketimNoktasi", b =>
                {
                    b.Property<long>("TuketimNoktasiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tuketim_noktasi_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TuketimNoktasiId"));

                    b.Property<string>("AcikAdres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acik_adres");

                    b.Property<string>("BagimsizBolumNo")
                        .HasColumnType("text")
                        .HasColumnName("bagimsiz_bolum_no");

                    b.Property<string>("BaglantiDurumu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("baglanti_durumu");

                    b.Property<decimal>("BaglantiGucuKw")
                        .HasColumnType("numeric")
                        .HasColumnName("baglanti_gucu_kw");

                    b.Property<string>("BinaNo")
                        .HasColumnType("text")
                        .HasColumnName("bina_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<int>("IlceId")
                        .HasColumnType("integer")
                        .HasColumnName("ilce_id");

                    b.Property<decimal?>("KoordinatLat")
                        .HasColumnType("numeric")
                        .HasColumnName("koordinat_lat");

                    b.Property<decimal?>("KoordinatLon")
                        .HasColumnType("numeric")
                        .HasColumnName("koordinat_lon");

                    b.Property<string>("Mahalle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mahalle");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TekilKod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tekil_kod");

                    b.Property<string>("TuketiciGrubu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tuketici_grubu");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.HasKey("TuketimNoktasiId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IlceId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("tuketim_noktasi");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.AuditLog", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.Kullanicilar", "Kullanici")
                        .WithMany("AuditLogs")
                        .HasForeignKey("KullaniciId")
                        .HasConstraintName("fk_audit_log_kullanici");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.EndeksOkuma", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.IsEmirleri", "IsEmri")
                        .WithMany("EndeksOkumas")
                        .HasForeignKey("IsEmriId");

                    b.HasOne("KcetasAboneApi.Models.Kullanicilar", "Kullanici")
                        .WithMany("EndeksOkumas")
                        .HasForeignKey("KullaniciId");

                    b.HasOne("KcetasAboneApi.Models.Sayaclar", "Sayac")
                        .WithMany("EndeksOkumas")
                        .HasForeignKey("SayacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KcetasAboneApi.Models.Sozlesmeler", "Sozlesme")
                        .WithMany("EndeksOkumas")
                        .HasForeignKey("SozlesmeId");

                    b.Navigation("IsEmri");

                    b.Navigation("Kullanici");

                    b.Navigation("Sayac");

                    b.Navigation("Sozlesme");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.EntegrasyonOutbox", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.Fatura", "Fatura")
                        .WithMany("EntegrasyonOutboxes")
                        .HasForeignKey("FaturaId")
                        .IsRequired()
                        .HasConstraintName("fk_entegrasyon_outbox_fatura");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Fatura", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.EndeksOkuma", "Okuma")
                        .WithMany("Faturas")
                        .HasForeignKey("OkumaId")
                        .HasConstraintName("fk_fatura_okuma");

                    b.HasOne("KcetasAboneApi.Models.Sozlesmeler", "Sozlesme")
                        .WithMany("Faturas")
                        .HasForeignKey("SozlesmeId")
                        .IsRequired()
                        .HasConstraintName("fk_fatura_sozlesme");

                    b.Navigation("Okuma");

                    b.Navigation("Sozlesme");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.FaturaKalemi", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.Fatura", "Fatura")
                        .WithMany("FaturaKalemis")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fatura_kalemi_fatura");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Ilce", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.Il", "Il")
                        .WithMany("Ilces")
                        .HasForeignKey("IlId")
                        .IsRequired()
                        .HasConstraintName("fk_ilce_il");

                    b.Navigation("Il");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.IsEmirleri", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.Kullanicilar", "AtananKullanici")
                        .WithMany("IsEmirleris")
                        .HasForeignKey("AtananKullaniciId");

                    b.HasOne("KcetasAboneApi.Models.Sayaclar", "Sayac")
                        .WithMany("IsEmirleris")
                        .HasForeignKey("SayacId");

                    b.HasOne("KcetasAboneApi.Models.TuketimNoktasi", "TuketimNoktasi")
                        .WithMany("IsEmirleris")
                        .HasForeignKey("TuketimNoktasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtananKullanici");

                    b.Navigation("Sayac");

                    b.Navigation("TuketimNoktasi");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Kullanicilar", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.Roller", "Rol")
                        .WithMany("Kullanicilars")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("fk_kullanicilar_roller");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Sayaclar", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.Kullanicilar", "CreatedByNavigation")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("KcetasAboneApi.Models.TuketimNoktasi", "TuketimNoktasi")
                        .WithMany("Sayaclars")
                        .HasForeignKey("TuketimNoktasiId");

                    b.HasOne("KcetasAboneApi.Models.Kullanicilar", "UpdatedByNavigation")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("TuketimNoktasi");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Sozlesmeler", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.Aboneler", "Abone")
                        .WithMany("Sozlesmelers")
                        .HasForeignKey("AboneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KcetasAboneApi.Models.Tarifeler", "Tarife")
                        .WithMany()
                        .HasForeignKey("TarifeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KcetasAboneApi.Models.TuketimNoktasi", "TuketimNoktasi")
                        .WithMany("Sozlesmelers")
                        .HasForeignKey("TuketimNoktasiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abone");

                    b.Navigation("Tarife");

                    b.Navigation("TuketimNoktasi");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.TuketimNoktasi", b =>
                {
                    b.HasOne("KcetasAboneApi.Models.Kullanicilar", "CreatedByNavigation")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("KcetasAboneApi.Models.Ilce", "Ilce")
                        .WithMany("TuketimNoktasis")
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KcetasAboneApi.Models.Kullanicilar", "UpdatedByNavigation")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Ilce");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Aboneler", b =>
                {
                    b.Navigation("Sozlesmelers");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.EndeksOkuma", b =>
                {
                    b.Navigation("Faturas");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Fatura", b =>
                {
                    b.Navigation("EntegrasyonOutboxes");

                    b.Navigation("FaturaKalemis");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Il", b =>
                {
                    b.Navigation("Ilces");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Ilce", b =>
                {
                    b.Navigation("TuketimNoktasis");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.IsEmirleri", b =>
                {
                    b.Navigation("EndeksOkumas");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Kullanicilar", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("EndeksOkumas");

                    b.Navigation("IsEmirleris");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Roller", b =>
                {
                    b.Navigation("Kullanicilars");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Sayaclar", b =>
                {
                    b.Navigation("EndeksOkumas");

                    b.Navigation("IsEmirleris");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.Sozlesmeler", b =>
                {
                    b.Navigation("EndeksOkumas");

                    b.Navigation("Faturas");
                });

            modelBuilder.Entity("KcetasAboneApi.Models.TuketimNoktasi", b =>
                {
                    b.Navigation("IsEmirleris");

                    b.Navigation("Sayaclars");

                    b.Navigation("Sozlesmelers");
                });
#pragma warning restore 612, 618
        }
    }
}
